; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	c:\data\AsmBook5\examples\ch08\C_Examples\C_Examples\makeArray.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	__$ArrayPad$
PUBLIC	_makeArray
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
; Function compile flags: /Ogtpy
;	COMDAT _makeArray
_TEXT	SEGMENT
__$ArrayPad$ = -4					; size = 4
_makeArray PROC						; COMDAT
; File c:\data\asmbook5\examples\ch08\c_examples\c_examples\makearray.c
; Line 4
	sub	esp, 36					; 00000024H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+36], eax
; Line 8
	xor	eax, eax
$LL3@makeArray:
	add	eax, 1
	cmp	eax, 30					; 0000001eH
	jl	SHORT $LL3@makeArray
; Line 11
	mov	ecx, DWORD PTR __$ArrayPad$[esp+36]
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 36					; 00000024H
	ret	0
_makeArray ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Ogtpy
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT
; Line 20
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
END
